apiVersion: v1
kind: Secret
metadata:
  name: google-oauth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  GOOGLE_CLIENT_ID: {{ .Values.googleClientId | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.googleClientSecret | b64enc }}