apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
data:
  JWT_SECRET_KEY: {{ .Values.jwtSecret }}
  DEBUG: {{ if eq .Values.global.environment "development" }}"True"{{ else }}"False"{{ end }}
  KAFKA_BROKER_URL: "kafka:9093"
  KAFKA_CONSUMER_GROUP: "reservation-service"