apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: user-service
spec:
  replicas: {{ .Values.services.user.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: {{ .Values.imageRegistry }}/{{ .Values.imageRepository }}/user-service:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.services.user.port }}
        env:
        - name: DATABASE_URL
          value: postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/user_db
        - name: JWT_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JWT_SECRET_KEY
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DEBUG
        - name: PORT
          value: "{{ .Values.services.user.port }}"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-oauth-secret
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-oauth-secret
              key: GOOGLE_CLIENT_SECRET
        - name: ADMIN_EMAILS
          value: "{{ .Values.adminEmails }}"
        readinessProbe:
          httpGet:
            path: /users/
            port: {{ .Values.services.user.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /users/
            port: {{ .Values.services.user.port }}
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
{{ toYaml .Values.services.user.resources | indent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: user-service
  ports:
  - port: {{ .Values.services.user.port }}
    targetPort: {{ .Values.services.user.port }}