apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
  namespace: meeting-room-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
      - name: room-service
        image: room-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@postgres:5432/room_db
        - name: JWT_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JWT_SECRET_KEY
        - name: KAFKA_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_BROKER_URL
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DEBUG
        - name: PORT
          value: "5001"
        readinessProbe:
          httpGet:
            path: /rooms/
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /rooms/
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: room-service
  namespace: meeting-room-system
spec:
  selector:
    app: room-service
  ports:
  - port: 5001
    targetPort: 5001