apiVersion: v2
name: meeting-room-system
description: Helm chart for Meeting Room Reservation System
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: DevOps Team
    email: devops@example.com