# Default values for meeting-room-system Helm chart
# This is a YAML-formatted file.

# Global configuration
global:
  environment: development # Options: development, staging, production

# Image configuration
imageRegistry: gcr.io
imageRepository: mohamedlandolsi # Will be overridden by your GCP project ID
imageTag: latest
imagePullPolicy: IfNotPresent

# Secrets and configuration
jwtSecret: "your-secret-key-here" # Overridden by deployment
googleClientId: "374852139175-3mku2c01depioeq5pgp170up5f0sllg3.apps.googleusercontent.com" 
googleClientSecret: "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"
adminEmails: "mohamedlandolsi30@gmail.com"

# Database configuration
postgres:
  enabled: true
  persistence: true
  storageSize: 1Gi
  user: postgres
  password: postgres
  databases:
    - user_db
    - room_db
    - reservation_db

# Kafka configuration
kafka:
  enabled: true
  replicaCount: 1
  zookeeper:
    enabled: true
    replicaCount: 1

# Microservices configuration
services:
  user:
    name: user-service
    replicaCount: 2
    port: 5000
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  
  room:
    name: room-service
    replicaCount: 2
    port: 5001
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  
  reservation:
    name: reservation-service
    replicaCount: 2
    port: 5002
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

# NGINX configuration
nginx:
  enabled: true
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 80

# Monitoring configuration
monitoring:
  enabled: true
  
  # Loki configuration
  loki:
    enabled: true
    persistence:
      enabled: true
      storageSize: 10Gi
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  
  # Promtail configuration (log collector for Loki)
  promtail:
    enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
        
  # Grafana configuration
  grafana:
    enabled: true
    adminPassword: "admin" # Should be overridden in production
    persistence:
      enabled: true
      storageSize: 2Gi
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    dashboards:
      enabled: true
    alerting:
      enabled: true
      alertmanager:
        enabled: true
    service:
      type: ClusterIP
      port: 3000
    ingress:
      enabled: false # Set to true if you want to access Grafana via Ingress

  # AWS CloudWatch configuration
  cloudwatch:
    enabled: true
    region: "us-east-1" # Replace with your AWS region
    logGroupName: "meeting-room-reservation-system"
    logStreamPrefix: "kubernetes"
    fluentd:
      enabled: true
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi